FROM --platform=linux/amd64 rust:1.85 as builder

RUN apt update && apt install -y libssl-dev pkg-config ca-certificates curl

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release || true

COPY . .
RUN cargo build --release
